### PR TITLE
Fix #9

### LINKED ISSUE #9: Game cache connecting to repository item not working
Connecting a non-steam game to a repository item does nothing

### PR DESCRIPTION
**Pull request by DatL4g**
This will fix #9

### CODE REVIEW

File: src/main/kotlin/dev/datlag/dxvkotool/model/game/Game.kt [hunk 1]
```diff
@@ -17,6 +17,7 @@ import kotlinx.coroutines.flow.distinctUntilChanged
 import kotlinx.coroutines.flow.flatMapLatest
 import kotlinx.coroutines.flow.flow
 import kotlinx.coroutines.flow.transform
```
Comment (DatL4g) [inline src/main/kotlin/dev/datlag/dxvkotool/model/game/Game.kt]: Remove unused imports

File: src/main/kotlin/dev/datlag/dxvkotool/db/DB.kt [hunk 2]
```diff
@@ -13,8 +13,10 @@ import dev.datlag.sqldelight.db.SteamGame
 import kotlinx.coroutines.Dispatchers
 import kotlinx.coroutines.flow.Flow
 import kotlinx.coroutines.flow.MutableStateFlow
+import kotlinx.coroutines.flow.conflate
 import kotlinx.coroutines.flow.flowOn
 import kotlinx.coroutines.flow.transform
```
Comment (DatL4g) [inline src/main/kotlin/dev/datlag/dxvkotool/db/DB.kt]: Remove unused imports
